name: slpy
dependencies:
- cycler=0.9.0=py27_0
- freetype=2.5.5=0
- libpng=1.6.17=0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0
- numpy=1.10.4=py27_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py27_0
- pip=8.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py27_0
- setuptools=19.6.2=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - dimarray==0.2.3

